Repository LLNL/Tribol, pull requests merged in 2024-01, with the labels that each got.

#51 Use mfem target if exists
  cmake/SetupThirdParty.cmake
Labels: bug

#38 Redecomp sparse matrix transfers
  src/examples/CMakeLists.txt
  src/examples/element_matrix_redecomp.cpp
  src/examples/sparse_matrix_redecomp.cpp
  src/redecomp/CMakeLists.txt
  src/redecomp/RedecompMesh.cpp
  src/redecomp/RedecompMesh.hpp
  src/redecomp/redecomp.hpp
  src/redecomp/transfer/MatrixTransfer.cpp
  src/redecomp/transfer/SparseMatrixTransfer.cpp
  src/redecomp/transfer/SparseMatrixTransfer.hpp
  src/tests/CMakeLists.txt
  src/tests/redecomp_sparsematrix.cpp
Labels: enhancement

#55 clarify the output blocks of the jacobian
  src/tribol/interface/mfem_tribol.hpp
  src/tribol/mesh/MfemData.cpp
Labels: documentation
